[workspace]
channels = ["conda-forge", "bioconda"]
name = "metrics"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
# Python
python = ">=3.12"
scikit-learn = "*"
h5py = "*"
numpy = "*"
polars = "*"
# R
r-base = ">=4.5"
r-argparse = "*"
r-jsonlite = "*"
bioconductor-biocversion = "3.22.*"
bioconductor-poem = "*"
